tabs:
  general:
    display: General
    sections:
      -
        fields:
          - handle: simple_popup
            field:
              default: false
              type: toggle
              display: 'Simple Cookie Popup'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              instructions: 'Changes the popup to a simpler view with 2 buttons instead of checkboxes'
          -
            handle: cookie_lifetime
            field:
              default: '30'
              type: integer
              display: 'Cookie Lifetime (days)'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: necessary
            field:
              antlers: false
              type: textarea
              display: Necessary
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              instructions: 'E.g. <code>&lt;script&gt;// script that sets cookie&lt;/script&gt;</code> or  <code>&lt;script src="https://alt-design.net/cookie.js" &gt;&lt;/script&gt;</code>'
          -
            handle: enable_analytics
            field:
              default: true
              type: toggle
              display: 'Enable Analytics'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              width: 25
          -
            handle: enable_analytics_default
            field:
              default: true
              type: toggle
              display: 'Enable Analytics By Default'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              width: 50
          -
            handle: analytics
            field:
              antlers: false
              type: textarea
              display: Analytics
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: enable_advertising
            field:
              default: false
              type: toggle
              display: 'Enable Advertising'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              width: 25
          -
            handle: enable_advertising_default
            field:
              default: false
              type: toggle
              display: 'Enable Advertising By Default'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
              width: 50
          -
            handle: advertising
            field:
              antlers: false
              type: textarea
              display: Advertising
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
  google:
    display: Google
    sections:
      -
        fields:
          - handle: enable_google
            field:
              default: false
              type: toggle
              display: 'Enable Google'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
          -
            handle: google_tag_id
            field:
              input_type: text
              antlers: false
              type: text
              display: 'Google Tag ID'
              listable: hidden
              instructions_position: above
              visibility: visible
              replicator_preview: true
              hide_display: false
title: Settings
